-- TRAIN
drop table FCO_LOOKALIKE_TRAIN;
create table FCO_LOOKALIKE_TRAIN compress for query high pctfree 0
as
select GROUP_LOYALTY_MEMBER_NUMBER,
MOSAIC_DESC,
LIFESTAGE_HIGH_NAME,
FES_Y,
AGE_BAND,
OPENER_6M_ALL,
SURV_RESP_WW,
SURV_RESP_RW,
SURV_RESP_SW,
SURV_RESP_B,
SURV_RESP_S,
SURV_RESP_PM,
SURV_RESP_NONE,
MBR_GENDER,
CUSTOMER_AFFLUENCE,
POINTS_SEGMENT,
ONLINESHOPPING_YR,
NO_TRANS,
DAYS_SINCE_LAST_TRN,
TOTAL_SALES,
LL_DT,
FC_DT,
BEER_QTY,
BEER_SALES,
BEER_TRANS,
BEER_SALES_S,
BEER_QTY_S,
WINE_QTY,
WINE_SALES,
WINE_TRANS,
WINE_SALES_S,
WINE_QTY_S,
SPIRITS_QTY,
SPIRITS_SALES,
SPIRITS_TRANS,
SPIRITS_SALES_S,
SPIRITS_QTY_S,
0 as FCO_CST
from (
select a.*, DECODE(MOD(ROW_NUM, 11), 3, 'Y', 'N') as CONTROL_FLAG 
FROM (
select A.*,
ROW_NUMBER() over (order by 
                                            MOSAIC_DESC,
                                            LIFESTAGE_HIGH_NAME,
                                            FES_Y,
                                            AGE_BAND,
                                            OPENER_6M_ALL,
                                            SURV_RESP_WW,
                                            SURV_RESP_RW,
                                            SURV_RESP_SW,
                                            SURV_RESP_B,
                                            SURV_RESP_S,
                                            SURV_RESP_PM,
                                            SURV_RESP_NONE,
                                            MBR_GENDER,
                                            CUSTOMER_AFFLUENCE,
                                            POINTS_SEGMENT,
                                            ONLINESHOPPING_YR,
                                            NO_TRANS,
                                            DAYS_SINCE_LAST_TRN,
                                            TOTAL_SALES,
                                            LL_DT,
                                            FC_DT,
                                            BEER_QTY,
                                            BEER_SALES,
                                            BEER_TRANS,
                                            BEER_SALES_S,
                                            BEER_QTY_S,
                                            WINE_QTY,
                                            WINE_SALES,
                                            WINE_TRANS,
                                            WINE_SALES_S,
                                            WINE_QTY_S,
                                            SPIRITS_QTY,
                                            SPIRITS_SALES,
                                            SPIRITS_TRANS,
                                            SPIRITS_SALES_S,
                                            SPIRITS_QTY_S,
                                            DBMS_RANDOM.value) as ROW_NUM
from FCO_LOOKALIKE_COMPLETE a
where FCO_CST = 'N'
) a
)
where CONTROL_FLAG = 'Y'

union

select GROUP_LOYALTY_MEMBER_NUMBER,
MOSAIC_DESC,
LIFESTAGE_HIGH_NAME,
FES_Y,
AGE_BAND,
OPENER_6M_ALL,
SURV_RESP_WW,
SURV_RESP_RW,
SURV_RESP_SW,
SURV_RESP_B,
SURV_RESP_S,
SURV_RESP_PM,
SURV_RESP_NONE,
MBR_GENDER,
CUSTOMER_AFFLUENCE,
POINTS_SEGMENT,
ONLINESHOPPING_YR,
NO_TRANS,
DAYS_SINCE_LAST_TRN,
TOTAL_SALES,
LL_DT,
FC_DT,
BEER_QTY,
BEER_SALES,
BEER_TRANS,
BEER_SALES_S,
BEER_QTY_S,
WINE_QTY,
WINE_SALES,
WINE_TRANS,
WINE_SALES_S,
WINE_QTY_S,
SPIRITS_QTY,
SPIRITS_SALES,
SPIRITS_TRANS,
SPIRITS_SALES_S,
SPIRITS_QTY_S,
1 as FCO_CST
from FCO_LOOKALIKE_COMPLETE a
where FCO_CST = 'Y';


-- TEST
drop table FCO_LOOKALIKE_TEST;
create table FCO_LOOKALIKE_TEST compress for query high pctfree 0
as
select GROUP_LOYALTY_MEMBER_NUMBER,
MOSAIC_DESC,
LIFESTAGE_HIGH_NAME,
FES_Y,
AGE_BAND,
OPENER_6M_ALL,
SURV_RESP_WW,
SURV_RESP_RW,
SURV_RESP_SW,
SURV_RESP_B,
SURV_RESP_S,
SURV_RESP_PM,
SURV_RESP_NONE,
MBR_GENDER,
CUSTOMER_AFFLUENCE,
POINTS_SEGMENT,
ONLINESHOPPING_YR,
NO_TRANS,
DAYS_SINCE_LAST_TRN,
TOTAL_SALES,
LL_DT,
FC_DT,
BEER_QTY,
BEER_SALES,
BEER_TRANS,
BEER_SALES_S,
BEER_QTY_S,
WINE_QTY,
WINE_SALES,
WINE_TRANS,
WINE_SALES_S,
WINE_QTY_S,
SPIRITS_QTY,
SPIRITS_SALES,
SPIRITS_TRANS,
SPIRITS_SALES_S,
SPIRITS_QTY_S,
0 as FCO_CST
from FCO_LOOKALIKE_COMPLETE a
where FCO_CST = 'N';


--
SELECT COUNT(*), COUNT(DISTINCT GROUP_LOYALTY_MEMBER_NUMBER), FCO_CST FROM FCO_LOOKALIKE_TRAIN GROUP BY FCO_CST;