--MOSAIC_DESC
select COUNT(*), MOSAIC_DESC, FCO_CST from FCO_LOOKALIKE_COMPLETE
group by MOSAIC_DESC, FCO_CST
ORDER BY 3,2;

--LIFESTAGE
select COUNT(*), LIFESTAGE_HIGH_NAME, FCO_CST from FCO_LOOKALIKE_COMPLETE
group by LIFESTAGE_HIGH_NAME, FCO_CST
ORDER BY 3,2;

--AGE_BAND
select COUNT(*), AGE_BAND, FCO_CST from FCO_LOOKALIKE_COMPLETE
group by AGE_BAND, FCO_CST
ORDER BY 3,2;

--SURV_RESP
select COUNT(*),FCO_CST, SURV_RESP_WW,SURV_RESP_RW, SURV_RESP_SW,SURV_RESP_B,SURV_RESP_S,SURV_RESP_PM,SURV_RESP_NONE from FCO_LOOKALIKE_COMPLETE
group by FCO_CST,SURV_RESP_WW,SURV_RESP_RW, SURV_RESP_SW,SURV_RESP_B,SURV_RESP_S,SURV_RESP_PM,SURV_RESP_NONE
ORDER BY 2;

--MBR_GENDER
select COUNT(*), MBR_GENDER, FCO_CST from FCO_LOOKALIKE_COMPLETE
group by MBR_GENDER, FCO_CST
ORDER BY 3,2;

--CUSTOMER_AFFLUENCE
select COUNT(*), CUSTOMER_AFFLUENCE, FCO_CST from FCO_LOOKALIKE_COMPLETE
group by CUSTOMER_AFFLUENCE, FCO_CST
ORDER BY 3,2;

--POINTS_SEGMENT
select COUNT(*), POINTS_SEGMENT, FCO_CST from FCO_LOOKALIKE_COMPLETE
group by POINTS_SEGMENT, FCO_CST
ORDER BY 3,2;

--ONLINESHOPPING_YR
select COUNT(*), ONLINESHOPPING_YR, FCO_CST from FCO_LOOKALIKE_COMPLETE
group by ONLINESHOPPING_YR, FCO_CST
ORDER BY 3,2;